language: node_js
node_js:
  - "0.10"
rvm:
  - 2.0.0
before_install:
  - npm install grunt-cli -g
  - gem update --system 2.0.0
  - gem --version 
before_script:
  - npm install grunt-cli -g
install: npm install
