exclude: [node_modules, bower.json, Gruntfile.js, package.json, LICENSE, README.md]
collections:
  selectedrepos:
    output: true
  selectedgists:
    output: true
company: IBM
org: Cloud Data Services Labs
